const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const appSource = fs.readFileSync(path.join(__dirname, 'js', 'app.js'), 'utf8');
const evoGovernanceSource = fs.readFileSync(path.join(__dirname, 'js', 'evo-governance.js'), 'utf8');
const indexSource = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf8');
const cssSource = fs.readFileSync(path.join(__dirname, 'styles.css'), 'utf8');

function assertContains(source, expected, message) {
  assert.equal(source.includes(expected), true, message || `expected source to contain ${expected}`);
}

assertContains(appSource, "evo_governance: '\u667a\u80fd\u4f53\u8bb0\u5fc6\u4e2d\u67a2'", 'menu label should expose the memory hub');
assertContains(appSource, "items: ['account_settings', 'digital_human_settings', 'evo_governance'", 'system governance section should include memory hub');
assertContains(appSource, "evo_governance: ['admin', 'store_manager']", 'memory hub should be available to management roles');
assertContains(appSource, 'function renderEvoGovernancePage(container)', 'memory hub page renderer should exist');
assertContains(appSource, 'evo_governance: renderEvoGovernancePage', 'memory hub renderer should be registered');
assertContains(appSource, "label: '\u603b\u89c8'", 'memory hub should expose lifecycle overview tab');
assertContains(appSource, "label: '\u53cd\u9988\u6c89\u6dc0'", 'memory hub should expose feedback deposition tab');
assertContains(appSource, "label: '\u8bb0\u5fc6\u5173\u7cfb'", 'memory hub should expose memory lineage tab');
assertContains(appSource, "label: '\u5347\u7ea7\u5ba1\u6279'", 'memory hub should expose promotion approval tab');
assertContains(appSource, "label: '\u5b89\u5168\u7f51'", 'memory hub should expose safety tab');
assertContains(appSource, 'function evoGovAllowedTabsForRole(role)', 'memory hub should compute role-specific tabs');
assertContains(appSource, "return ['overview', 'feedback', 'lineage'];", 'store managers should only see the operational memory hub tabs');
assertContains(appSource, "return EVO_GOV_TABS.map(function (tab) { return tab.key; });", 'admins should keep all memory hub tabs');
assertContains(appSource, 'function evoGovNormalizeActiveTabForRole(state, role)', 'memory hub should reset unavailable tabs when role changes');
assertContains(appSource, 'EVO_GOV_TABS.filter(function (tab) { return allowedTabs.indexOf(tab.key) !== -1; })', 'tab navigation should render only allowed tabs');
assertContains(appSource, '].filter(function (card) { return allowedTabs.indexOf(card.key) !== -1; });', 'overview quick entries should follow the same role-specific tabs');
assertContains(appSource, "if (normalizeRole(role) === 'store_manager' && state.scopeType === 'global') state.scopeType = '';", 'store managers should not keep a global memory filter');
assertContains(appSource, "normalizeRole(getCurrentRole()) === 'store_manager'", 'store manager memory filters should explicitly hide global scope');
assertContains(appSource, 'function renderEvoGovernanceFeedbackTab()', 'feedback deposition tab renderer should exist');
assertContains(appSource, 'window.AgentO.renderEvoFeedbackHtml', 'answer cards should render evo feedback controls');
assertContains(appSource, 'function submitEvoEpisodeFeedback(episodeId, signal)', 'feedback controls should submit useful/useless signals');
assertContains(appSource, 'function submitEvoEpisodeCorrection(episodeId)', 'feedback controls should submit corrections');
assertContains(appSource, "'/api/evo/episodes/' + encodeURIComponent(id) + '/feedback'", 'feedback controls should call the feedback endpoint');
assertContains(appSource, "'/api/evo/episodes/' + encodeURIComponent(id) + '/correction'", 'correction controls should call the correction endpoint');
assertContains(appSource, 'function evoGovernanceDecideReview(id, decision)', 'overview should let managers approve or reject candidate memories');
assertContains(appSource, "'/api/evo/review-queue/' + encodeURIComponent(String(id)) + '/decision'", 'review decision endpoint should be consumed');
assertContains(appSource, 'function loadEvoGovernanceFeedbackEvents(options)', 'feedback tab should load raw feedback events');
assertContains(appSource, 'function renderEvoGovernanceFeedbackEventCard(item)', 'feedback tab should render raw feedback event cards');
assertContains(appSource, 'function renderEvoGovernanceAttentionList(pendingReviews, recentAnomalies)', 'overview should foreground work that needs attention');
assertContains(appSource, 'function renderEvoGovernanceQuickEntryCards(overview)', 'overview should provide simple action entry cards');
assertContains(appSource, 'function renderEvoGovernancePipelineHealth(overview)', 'overview should explain the real data pipeline health');
assertContains(appSource, 'function renderEvoGovernanceScanSummary(summary)', 'scan actions should render their latest real summary');
assertContains(appSource, 'function renderEvoGovernanceDiagnosticEmptyState(kind, diagnostics)', 'empty governance tabs should explain why real data is absent');
assertContains(appSource, 'function renderEvoGovernancePromotionCandidatePreview(diagnostics)', 'promotion tab should render candidate preview diagnostics');
assertContains(appSource, 'function renderEvoGovernanceEvalFilters()', 'safety tab should render eval case governance filters');
assertContains(appSource, 'function evoGovernanceAdvancePipeline()', 'overview should expose a manual real-pipeline advance action');
assertContains(appSource, 'function renderEvoGovernanceMemoryCard(item, mode)', 'memory list should render scannable summary cards');
assertContains(appSource, 'function renderEvoGovernanceRelationshipChain(detail)', 'memory detail should render a relationship chain');
assertContains(appSource, 'function renderEvoGovernanceSourceRow(pair)', 'memory source rows should render full feedback context');
assertContains(appSource, 'function evoGovEpisodeSignalLabel(signal, episodeType)', 'memory source rows should label user feedback signals');
assertContains(appSource, 'EVO_GOV_AUDIT_ACTION_LABELS', 'memory hub should translate audit action codes');
assertContains(appSource, 'EVO_GOV_TARGET_TYPE_LABELS', 'memory hub should translate target type codes');
assertContains(appSource, 'evoGovFormatConfidence(item.confidence)', 'memory list should show confidence as a readable percentage');
assertContains(appSource, '\u5f85\u5904\u7406\u4e8b\u9879', 'overview should label pending work in a natural operations tone');
assertContains(appSource, 'function evoGovAttentionTitle(text)', 'overview should clean technical reason prefixes before display');
assertContains(appSource, '\u67e5\u770b\u53cd\u9988\u3001\u8bb0\u5fc6\u3001\u5ba1\u6279\u4e0e\u5b89\u5168\u72b6\u6001', 'page subtitle should be Chinese and task-focused');
assertContains(appSource, '\u6570\u636e\u94fe\u8def', 'memory hub should label pipeline data clearly');
assertContains(appSource, 'id="evo-gov-pipeline-advance">推进</button>', 'memory hub should let managers advance existing real feedback through the pipeline');
assertContains(appSource, "'/api/evo/pipeline/advance'", 'pipeline advance endpoint should be consumed');
assertContains(appSource, '\u4e0d\u8865\u9020\u547d\u4e2d\u6216\u5347\u7ea7\u63d0\u8bae', 'pipeline copy should state it does not fake hits or promotions');
assertContains(appSource, '\u6682\u65e0\u53ef\u5347\u7ea7\u63d0\u8bae', 'promotion empty state should be specific');
assertContains(appSource, '\u5019\u9009\u9884\u89c8', 'promotion tab should show candidate preview copy');
assertContains(indexSource, 'js/evo-governance.js', 'memory hub helper script should be loaded separately');
assertContains(appSource, 'window.AgentOEvoGovernance.renderPreflightBadge(item.preflight)', 'promotion tab should use the split governance helper');
assertContains(evoGovernanceSource, 'function renderPreflightBadge(preflight)', 'promotion tab should render preflight badges');
assertContains(appSource, '\u524d\u7f6e\u68c0\u67e5', 'promotion table should expose preflight check column');
assertContains(evoGovernanceSource, '\u672a\u8fd0\u884c', 'preflight badge should label not-run state');
assertContains(evoGovernanceSource, '\u901a\u8fc7', 'preflight badge should label passed state');
assertContains(evoGovernanceSource, '\u963b\u65ad', 'preflight badge should label blocked state');
assertContains(evoGovernanceSource, '\u7f3a\u7528\u4f8b', 'preflight badge should label missing-case state');
assertContains(appSource, '\u5bfc\u5165\u5408\u89c4\u57fa\u7ebf', 'eval case seed action should use compliance baseline copy');
assertContains(appSource, '\u5bfc\u5165\u5408\u89c4\u57fa\u7ebf\u5931\u8d25', 'eval case seed failure toast should use compliance baseline copy');
assertContains(appSource, 'EVO_GOV_EVAL_CASE_SOURCE_LABELS', 'eval cases should translate source governance labels');
assertContains(appSource, "params.set('source', state.evalCaseSource)", 'eval case list should support source filtering');
assertContains(appSource, 'id="evo-gov-eval-source"', 'safety tab should expose source filter');
assertContains(appSource, 'id="evo-gov-eval-module"', 'safety tab should expose module filter');
assertContains(appSource, 'id="evo-gov-eval-severity"', 'safety tab should expose severity filter');
assertContains(appSource, '\u6ca1\u6709\u53ef\u626b\u63cf\u7684\u6280\u80fd\u89c4\u5219', 'promotion diagnostics should explain missing procedural data');
assertContains(appSource, '\u5b89\u5168\u7f51\u5df2\u8fd0\u884c\u4e14\u6682\u65e0\u5f02\u5e38', 'safety empty state should distinguish healthy zero from missing data');
assertContains(appSource, '\u770b\u8be6\u60c5', 'memory cards should expose a plain detail action');
assertContains(appSource, 'data-evo-action="enable">启用</button>', 'memory detail should allow disabled memories to be enabled again');
assertContains(appSource, "action === 'enable'", 'memory governance action should handle enable requests');
assertContains(appSource, "body: JSON.stringify({ status: 'active' })", 'enable action should reactivate the memory through the existing update endpoint');
assertContains(appSource, 'function renderEvoGovernanceSafetyTab()', 'safety tab renderer should exist');
assertContains(appSource, "state.activeTab === 'feedback'", 'feedback tab should load filtered memories');
assertContains(appSource, "state.activeTab === 'lineage'", 'memory lineage tab should load memories');
assertContains(appSource, "state.activeTab === 'safety'", 'safety tab should load eval and anomalies');
assertContains(appSource, 'var hasDetailPane = requestLoading', 'memory hub should not reserve detail column before a memory is selected');
assertContains(appSource, "(hasDetailPane ? renderEvoGovernanceMemoryDetail() : '')", 'memory hub should render detail only when needed');
assertContains(appSource, '\u5173\u7cfb\u94fe', 'memory detail should foreground the relationship chain');
assertContains(appSource, '\u6765\u6e90\u53cd\u9988', 'memory detail should show source feedback');
assertContains(appSource, '\u547d\u4e2d\u56de\u7b54', 'memory detail should show answer hit history');
assertContains(appSource, '\u540e\u7eed\u5f71\u54cd', 'memory detail should show derived impact');
assertContains(appSource, '\u98ce\u9669\u4e0e\u5f85\u5ba1', 'memory detail should show safety and review status');
assertContains(appSource, '\u539f\u95ee\u9898', 'source feedback should show the original question');
assertContains(appSource, '\u667a\u80fd\u4f53\u539f\u56de\u7b54', 'source feedback should show the original assistant answer in Chinese');
assertContains(appSource, '\u7528\u6237\u53cd\u9988', 'source feedback should show user feedback text');
assertContains(appSource, 'step="0.01"', 'confidence editor should accept displayed confidence values without browser invalid state');
assertContains(appSource, '\u6709\u7528 / \u51c6', 'source feedback should label positive feedback');
assertContains(appSource, '\u6ca1\u7528 / \u4e0d\u51c6', 'source feedback should label negative feedback');
assertContains(appSource, "'/api/evo/governance/overview'", 'overview endpoint should be consumed');
assertContains(appSource, "'/api/evo/feedback-events?'", 'feedback event endpoint should be consumed');
assertContains(appSource, "'/api/evo/memories?'", 'memory list endpoint should be consumed');
assertContains(appSource, "'/api/evo/memories/' + type + '/' + id + '/rollback'", 'rollback endpoint should be consumed');
assertContains(appSource, 'function evoGovHasScrollableOverflow(el)', 'safety tab should detect scrollable list panes');
assertContains(appSource, 'function evoGovResolveWheelScrollTarget(root, target, deltaY)', 'safety tab should resolve wheel targets');
assertContains(appSource, 'function bindEvoGovernanceWheelScroll(root)', 'safety tab should bind wheel navigation');
assertContains(appSource, "bindEvoGovernanceWheelScroll(container.querySelector('.evo-gov-shell'));", 'safety page should activate wheel binding on the shell');
assertContains(cssSource, '.evo-gov-lifecycle', 'memory hub lifecycle layout styles should exist');
assertContains(cssSource, '.evo-gov-chain', 'memory relationship chain styles should exist');
assertContains(cssSource, '.evo-gov-stage-card', 'memory hub stage cards should exist');
assertContains(cssSource, '.evo-gov-feedback-badge', 'source feedback signal badge styles should exist');
assertContains(cssSource, '.evo-feedback-controls', 'answer feedback controls should be styled');
assertContains(cssSource, '.evo-gov-feedback-card', 'feedback event card styles should exist');
assertContains(cssSource, '.evo-gov-feedback-memory-chip', 'feedback events should link to deposited memories');
assertContains(cssSource, '.evo-gov-source-field__label', 'source feedback field styles should exist');
assertContains(cssSource, '.evo-gov-attention', 'overview attention panel styles should exist');
assertContains(cssSource, '.evo-gov-attention-actions', 'pending review actions should be styled');
assertContains(cssSource, '.evo-gov-quick-grid', 'overview quick entry layout should exist');
assertContains(cssSource, '.evo-gov-health-grid', 'pipeline health cards should be styled');
assertContains(cssSource, '.evo-gov-pipeline-note', 'pipeline guardrail note should be styled');
assertContains(cssSource, '.evo-gov-empty-diagnostic', 'diagnostic empty states should be styled');
assertContains(cssSource, '.evo-gov-scan-summary', 'scan summaries should be styled');
assertContains(cssSource, '.evo-gov-candidate-preview', 'promotion candidate preview should be styled');
assertContains(cssSource, '.evo-gov-preflight-badge', 'promotion preflight badges should be styled');
assertContains(cssSource, '.evo-gov-eval-filters', 'eval case governance filters should be styled');
assertContains(cssSource, '.evo-gov-filters.evo-gov-eval-filters', 'eval filters should override the generic filter grid to avoid overflow in half-width panels');
assertContains(cssSource, '.evo-gov-memory-card', 'memory summary card styles should exist');
assertContains(cssSource, '.evo-gov-source-compact-field', 'feedback cards should use compact source fields');
assertContains(cssSource, '.evo-gov-memory-layout', 'memory hub layout styles should exist');
assertContains(cssSource, '.evo-gov-safety-scroll', 'safety tab should use dedicated scroll panes for cases and runs');
assertContains(cssSource, 'grid-template-columns: repeat(auto-fit, minmax(96px, 1fr));', 'memory hub tabs should fit all labels without clipping');
assertContains(cssSource, 'overflow: visible;', 'memory hub tabs should not hide wrapped items');
assertContains(cssSource, 'grid-template-columns: repeat(2, minmax(0, 1fr));', 'memory hub tabs should switch to a compact mobile grid');
assertContains(cssSource, '.evo-gov-memory-layout--with-detail', 'memory hub detail layout should be explicitly controlled');
assertContains(cssSource, '@media (min-width: 1440px)', 'memory hub detail pane should only sit beside the list on wide screens');
assertContains(cssSource, 'grid-template-columns: minmax(0, 1fr) minmax(260px, 0.58fr) auto;', 'memory cards should keep dense facts readable on desktop');
assertContains(cssSource, '@media (max-width: 720px)', 'memory hub should include mobile responsive rules');

console.log('evo-governance.test.js passed');
